export const enum Education {
  DOCTORATE = 'DOCTORATE',

  NO_FORMAL_EDUCATION = 'NO_FORMAL_EDUCATION',

  BACHELOR = 'BACHELOR',

  PRIMARY = 'PRIMARY',

  SECONDARY_HIGH_SCHOOL = 'SECONDARY_HIGH_SCHOOL',

  MASTER = 'MASTER',

  PREFER_NOT_TO_ANSWER = 'PREFER_NOT_TO_ANSWER',
}
